# name: CI

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     strategy:
#       matrix:
#         node-version: [18.x]

#     steps:
#       - uses: actions/checkout@v4
#       - name: Use Node.js ${{ matrix.node-version }}
#         uses: actions/setup-node@v4
#         with:
#           node-version: ${{ matrix.node-version }}
#       - name: Install
#         run: npm install
#       - name: Test
#         run: npm test
#       - name: Lint
#         run: npm run lint
#       - name: Build
#         run: npm run build
